version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "415658325849"
    IMAGE_TAG: "lastest"
    REGION: "eu-central-1"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin 415658325849.dkr.ecr.eu-central-1.amazonaws.com
      - REPOSITORY_URI=415658325849.dkr.ecr.eu-central-1.amazonaws.com/drawify
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - docker run -d -p 3000:3000 -e PORT=5000  $REPOSITORY_URI:latest
      - echo "test drawify"